sections/multi-column.liquid, templates/index.json
[YSHOP2-148](https://youcanshop.atlassian.net/browse/YSHOP2-148)
[YSHOP2-148]: https://youcanshop.atlassian.net/browse/YSHOP2-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-148:As a seller, I would like to be able to add multiple columns

assets/product-quantity-input.js, assets/product.css, styles/product.scss
[YSHOP2-163](https://youcanshop.atlassian.net/browse/YSHOP2-163)
[YSHOP2-163]: https://youcanshop.atlassian.net/browse/YSHOP2-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-163: As a seller, I want to be able to add the quantity 

assets/main.css, assets/reviews.css, assets/reviews.js, snippets/head-config.liquid, snippets/product-home.liquid, snippets/reviews.liquid, styles/main.scss, styles/reviews.scss, templates/index.json
[YSHOP2-152](https://youcanshop.atlassian.net/browse/YSHOP2-152)
[YSHOP2-152]: https://youcanshop.atlassian.net/browse/YSHOP2-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-152: As a seller, I want to be able to add customer reviews

assets/reviews.css, config/settings_data.json, styles/reviews.scss
=> DARK: reviews

assets/footer.css, config/settings_data.json, sections/featured-collections.liquid, sections/main-footer.liquid, styles/footer.scss
[YSHOP2-158](https://youcanshop.atlassian.net/browse/YSHOP2-158)
[YSHOP2-158]: https://youcanshop.atlassian.net/browse/YSHOP2-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-158: As a seller, I want to be able to customize the footer

assets/collection-listing.css, locales/ar.default.json, locales/en.json, locales/fr.json, sections/main-list-collections.liquid, snippets/collection-preview.liquid, styles/collection-listing.scss
[YSHOP2-193](https://youcanshop.atlassian.net/browse/YSHOP2-193)
https://user-images.githubusercontent.com/117163420/227512054-dc332357-0b77-4ad1-9085-7313a53a98f3.mov
[YSHOP2-193]: https://youcanshop.atlassian.net/browse/YSHOP2-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-193: As a seller, I would like to be able to add the list of all collections in one page

assets/product-column.css, sections/product-column.liquid, sections/product.liquid, snippets/product-home.liquid, styles/product-column.scss, styles/product.scss, templates/index.json
[YSHOP2-157](https://youcanshop.atlassian.net/browse/YSHOP2-157)
[YSHOP2-157]: https://youcanshop.atlassian.net/browse/YSHOP2-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-157: As a seller, I want to be able to add a product column section

assets/main.css, assets/product.css, styles/main.scss, styles/product.scss
[DOT-X](https://youcanshop.atlassian.net/browse/DOT-X)
=> Fix: sticky product image

assets/express-checkout.css, assets/express-checkout.js, assets/main.css, sections/product.liquid, snippets/express-checkout.liquid, styles/express-checkout.scss, styles/main.scss
[YSHOP2-335](https://youcanshop.atlassian.net/browse/YSHOP2-335)
I have also add the validation error for custom input
[YSHOP2-335]: https://youcanshop.atlassian.net/browse/YSHOP2-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-335 : COD v2 > Express checkout bloc - Gap between input fields settings not working

snippets/product-home.liquid
=> DARK : COD V2 > Product column section > fix compare price value error

assets/main.js, sections/featured-collections.liquid
[YSHOP2-351](https://youcanshop.atlassian.net/browse/YSHOP2-351)
[YSHOP2-351]: https://youcanshop.atlassian.net/browse/YSHOP2-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-351 : The bottom padding setting is not working

sections/featured-collections.liquid
[YSHOP2-348](https://youcanshop.atlassian.net/browse/YSHOP2-348)
[DOT-348]: https://youcanshop.atlassian.net/browse/DOT-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YSHOP2-348]: https://youcanshop.atlassian.net/browse/YSHOP2-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-348: Featured collections > Removing the image upload setting

assets/reviews-count.js, assets/reviews.js, sections/product-reviews.liquid, sections/product.liquid, snippets/head-config.liquid, snippets/product-home.liquid, snippets/reviews.liquid
=> DARK : COD v2 > fix the visibility of reviews in Product & home pages

snippets/accordion.liquid
[YSHOP2-355](https://youcanshop.atlassian.net/browse/YSHOP2-355)
[YSHOP2-355]: https://youcanshop.atlassian.net/browse/YSHOP2-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-355 : COD v2 > Single product > Click event isn't show up the accordion details

sections/main-video.liquid
[YSHOP2-350](https://youcanshop.atlassian.net/browse/YSHOP2-350)
[YSHOP2-350]: https://youcanshop.atlassian.net/browse/YSHOP2-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-350: Video > The video section should have bottom and top padding settings

sections/desktop-slider.liquid
[YSHOP2-306](https://youcanshop.atlassian.net/browse/YSHOP2-306)
[YSHOP2-306]: https://youcanshop.atlassian.net/browse/YSHOP2-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-306

assets/desktop-slider.css, styles/desktop-slider.scss
[YSHOP2-358](https://youcanshop.atlassian.net/browse/YSHOP2-358)
[YSHOP2-358]: https://youcanshop.atlassian.net/browse/YSHOP2-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-358 : COD V2 > Slider > Display issue with the title

assets/cart-drawer.js, assets/main.css, assets/navbar.css, assets/product.js, styles/main.scss, styles/navbar.scss
[YSHOP2-359](https://youcanshop.atlassian.net/browse/YSHOP2-359)
[YSHOP2-359]: https://youcanshop.atlassian.net/browse/YSHOP2-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-359 : COD V2 > card drawer > Click functionality not working on delete icon

package.json, sections/feature-products-by-category.liquid, templates/index.json
[DOT-420](https://youcanshop.atlassian.net/browse/DOT-420)
[DOT-420]: https://youcanshop.atlassian.net/browse/DOT-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Section initial background color is not getting applied

sections/feature-products-by-category.liquid, templates/index.json
[YSHOP2-418](https://youcanshop.atlassian.net/browse/YSHOP2-418)
[YSHOP2-418]: https://youcanshop.atlassian.net/browse/YSHOP2-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-418: Wording update for section/blocks settings

assets/product-column.css, sections/product-column.liquid, styles/product-column.scss
[YSHOP2-364](https://youcanshop.atlassian.net/browse/YSHOP2-364)
screenshot
[YSHOP2-364]: https://youcanshop.atlassian.net/browse/YSHOP2-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-364 : COD V2 > Product column > product shape isn't look correct

sections/featured-product-slider.liquid, snippets/product-slider.liquid, templates/index.json
[DOT-360](https://youcanshop.atlassian.net/browse/DOT-360)
[DOT-360]: https://youcanshop.atlassian.net/browse/DOT-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-360: Product slider > UI bugs

assets/main.css, sections/featured-products.liquid, snippets/product-preview.liquid, styles/main.scss, templates/index.json
[DOT-361](https://youcanshop.atlassian.net/browse/DOT-361)
[DOT-361]: https://youcanshop.atlassian.net/browse/DOT-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Featured products > discount banner shape change after update the banner position 

sections/multi-column.liquid
[YSHOP2-362](https://youcanshop.atlassian.net/browse/YSHOP2-362)
[DOT-362]: https://youcanshop.atlassian.net/browse/DOT-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YSHOP2-362]: https://youcanshop.atlassian.net/browse/YSHOP2-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Multi-columns > UI bugs 

sections/feature-products-by-category.liquid
[YSHOP2-420](https://youcanshop.atlassian.net/browse/YSHOP2-420)
[YSHOP2-420]: https://youcanshop.atlassian.net/browse/YSHOP2-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-420: Section initial background color is not getting applied

sections/feature-products-by-category.liquid, templates/index.json
[YSHOP2-421](https://youcanshop.atlassian.net/browse/YSHOP2-421)
[YSHOP2-421]: https://youcanshop.atlassian.net/browse/YSHOP2-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-421: Dedicated setting for title text color

sections/main-footer.liquid
[YSHOP2-423](https://youcanshop.atlassian.net/browse/YSHOP2-423)
[YSHOP2-423]: https://youcanshop.atlassian.net/browse/YSHOP2-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove "Hide social media" toggle

sections/multi-column.liquid
[YSHOP2-429](https://youcanshop.atlassian.net/browse/YSHOP2-429)
[YSHOP2-429]: https://youcanshop.atlassian.net/browse/YSHOP2-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-429: COD v2 - Multi-column block description should accept text not html

assets/cart.js, assets/main.css, sections/main-cart.liquid, styles/main.scss
[YSHOP2-365](https://youcanshop.atlassian.net/browse/YSHOP2-365)
[YSHOP2-365]: https://youcanshop.atlassian.net/browse/YSHOP2-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-365 : COD V2 > cart page > min height is missing 

sections/desktop-slider.liquid
[YSHOP2-431](https://youcanshop.atlassian.net/browse/YSHOP2-431)
[YSHOP2-431]: https://youcanshop.atlassian.net/browse/YSHOP2-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-431: keep the same overlay setting for both versions (Desktop & Mobile)

sections/main-footer.liquid
[YSHOP2-432](https://youcanshop.atlassian.net/browse/YSHOP2-432)
[YSHOP2-432]: https://youcanshop.atlassian.net/browse/YSHOP2-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-432: Add toggle setting to hide the footer section

sections/multi-column.liquid
[YSHOP2-434](https://youcanshop.atlassian.net/browse/YSHOP2-434)
[YSHOP2-434]: https://youcanshop.atlassian.net/browse/YSHOP2-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-434: COD v2 - Fix default Columns count

templates/index.json
=> DARK: fix count range

sections/main-navbar.liquid
[YSHOP2-436](https://youcanshop.atlassian.net/browse/YSHOP2-436)
[YSHOP2-436]: https://youcanshop.atlassian.net/browse/YSHOP2-436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-436: Option to hide the nav-bar

config/settings_data.json, sections/main-navbar.liquid, snippets/head-config.liquid
[YSHOP2-442](https://youcanshop.atlassian.net/browse/YSHOP2-442)
[YSHOP2-442]: https://youcanshop.atlassian.net/browse/YSHOP2-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-442: remove the cart badge from global settings and add it to use the primary color

config/settings_schema.json, sections/desktop-slider.liquid, sections/feature-products-by-category.liquid, sections/featured-collections.liquid, sections/featured-product-slider.liquid, sections/featured-products.liquid, sections/main-express-checkout.liquid, sections/main-footer.liquid, sections/main-video.liquid, sections/multi-column.liquid, sections/notice-bar.liquid, sections/product-column.liquid, sections/product.liquid
[YSHOP2-437](https://youcanshop.atlassian.net/browse/YSHOP2-437)
[YSHOP2-437]: https://youcanshop.atlassian.net/browse/YSHOP2-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-437 : COD V2 ~ CLONE - Naming conventions, first letter uppercase only

sections/main-cart.liquid
[YSHOP2-449](https://youcanshop.atlassian.net/browse/YSHOP2-449)
-  [ ] Check the cart page, increase and decrease the quantity and see if it works
[YSHOP2-449]: https://youcanshop.atlassian.net/browse/YSHOP2-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-449: COD v2 - Cart page quantity update issue

assets/video.css, sections/main-video.liquid, styles/video.scss
[YSHOP2-448](https://youcanshop.atlassian.net/browse/YSHOP2-448)
[YSHOP2-448]: https://youcanshop.atlassian.net/browse/YSHOP2-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-448: Video section: Title doesn't work

sections/desktop-slider.liquid
[YSHOP2-X](https://youcanshop.atlassian.net/browse/YSHOP2-X)
=> YSHOP2-452: Pagination in mobile will only be displayed if both desktop & mobile pagination toggles are on

assets/navbar.css, sections/main-navbar.liquid, styles/navbar.scss
[YSHOP2-465](https://youcanshop.atlassian.net/browse/YSHOP2-465)
[YSHOP2-465]: https://youcanshop.atlassian.net/browse/YSHOP2-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-465: "Items and links color" setting not working

sections/desktop-slider.liquid
[YSHOP2-455](https://youcanshop.atlassian.net/browse/YSHOP2-455)
[YSHOP2-455]: https://youcanshop.atlassian.net/browse/YSHOP2-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-455: Font weight: 100-200-300 | 400-500 | 600-700-800-900 are the same weight as well

snippets/single-product.liquid
[YSHOP2-463](https://youcanshop.atlassian.net/browse/YSHOP2-463)
[YSHOP2-463]: https://youcanshop.atlassian.net/browse/YSHOP2-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-463 : COD V2 ~ CLONE - Express checkout button

sections/desktop-slider.liquid, sections/featured-product-slider.liquid
[YSHOP2-468](https://youcanshop.atlassian.net/browse/YSHOP2-468)
[YSHOP2-468]: https://youcanshop.atlassian.net/browse/YSHOP2-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-468 : COD V2 ~ CLONE - Update order & naming of some settings

assets/helper.js
[YSHOP2-469](https://youcanshop.atlassian.net/browse/YSHOP2-469)
[YSHOP2-469]: https://youcanshop.atlassian.net/browse/YSHOP2-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-469 : COD V2 ~ CLONE - Products Slider > Display countdown even if time runs out

sections/main-navbar.liquid
[YSHOP2-467](https://youcanshop.atlassian.net/browse/YSHOP2-467)
[YSHOP2-467]: https://youcanshop.atlassian.net/browse/YSHOP2-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-467: "Font family" should have a default value

templates/index.json
[YSHOP2-471](https://youcanshop.atlassian.net/browse/YSHOP2-471)
[YSHOP2-471]: https://youcanshop.atlassian.net/browse/YSHOP2-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-471: COD V2 > Multi column : Title position setting doesn't have a default value

assets/queries-handler.js, snippets/main-pagination.liquid
[YSHOP2-479](https://youcanshop.atlassian.net/browse/YSHOP2-479)
-  [ ]  go to collection page and open the console.log no errors any more
-  [ ] then test the pagination
[YSHOP2-479]: https://youcanshop.atlassian.net/browse/YSHOP2-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-479: COD v2 - The pagination doesn't work on click

sections/product-column.liquid, snippets/product-home.liquid, snippets/product-slider.liquid, snippets/single-product.liquid
[YSHOP2-477](https://youcanshop.atlassian.net/browse/YSHOP2-477)
[YSHOP2-477]: https://youcanshop.atlassian.net/browse/YSHOP2-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-477: COD v2 - Tag banner doesn't have a style

sections/featured-product-slider.liquid, snippets/product-slider.liquid
[YSHOP2-473](https://youcanshop.atlassian.net/browse/YSHOP2-473)
[YSHOP2-473]: https://youcanshop.atlassian.net/browse/YSHOP2-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-473:  COD V2 ~ Products slider section > fix bugs

assets/helper.js
[YSHOP2-500](https://youcanshop.atlassian.net/browse/YSHOP2-500)
[YSHOP2-500]: https://youcanshop.atlassian.net/browse/YSHOP2-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-500 : Countdown functionality triggering an infinite loop making the web page crush

sections/featured-product-slider.liquid, templates/index.json
[YSHOP2-491](https://youcanshop.atlassian.net/browse/YSHOP2-491)
[YSHOP2-491]: https://youcanshop.atlassian.net/browse/YSHOP2-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-491: COD-Theme 2 > Product slider > Fix UI bugs

sections/product-column.liquid, templates/index.json
[YSHOP2-496](https://youcanshop.atlassian.net/browse/YSHOP2-496)
[YSHOP2-496]: https://youcanshop.atlassian.net/browse/YSHOP2-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-496 : COD V2 > Product column > add missing option

assets/add-to-cart.js, assets/cart.js
[YSHOP2-497](https://youcanshop.atlassian.net/browse/YSHOP2-497)
[YSHOP2-497]: https://youcanshop.atlassian.net/browse/YSHOP2-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-497: The cart badge need to update with the sdk when the user add to cart

assets/cart.css, assets/cart.js, assets/collection-listing.css, sections/main-cart.liquid, styles/cart.scss, styles/collection-listing.scss
[YSHOP2-498](https://youcanshop.atlassian.net/browse/YSHOP2-498)
[YSHOP2-498]: https://youcanshop.atlassian.net/browse/YSHOP2-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-498: When you delete a product from the cart the total number of the products on the cart doesn't update

assets/cart-drawer.css, assets/cart-drawer.js, styles/cart-drawer.scss
[YSHOP2-504](https://youcanshop.atlassian.net/browse/YSHOP2-504)
[YSHOP2-504]: https://youcanshop.atlassian.net/browse/YSHOP2-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-504: When we add a product that has no variants it shouldn’t show in the card drawer as : default: default

assets/cart.js, assets/main.js, locales/ar.default.json, sections/main-cart.liquid, sections/main-search.liquid
[YSHOP2-505](https://youcanshop.atlassian.net/browse/YSHOP2-505)
[YSHOP2-505]: https://youcanshop.atlassian.net/browse/YSHOP2-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-505 : Search page > fix UI bugs

config/settings_data.json, sections/featured-products.liquid, sections/main-footer.liquid, sections/multi-column.liquid, templates/index.json
[YSHOP2-595](https://youcanshop.atlassian.net/browse/YSHOP2-595)
[YSHOP2-595]: https://youcanshop.atlassian.net/browse/YSHOP2-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-595 : COD v2 > Set the default text colors for some sections

templates/index.json
[YSHOP2-596](https://youcanshop.atlassian.net/browse/YSHOP2-596)
[YSHOP2-596]: https://youcanshop.atlassian.net/browse/YSHOP2-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-596: Default title in the product slider section - Theme 2

sections/desktop-slider.liquid, snippets/slider.liquid
[YSHOP2-608](https://youcanshop.atlassian.net/browse/YSHOP2-608)
[YSHOP2-608]: https://youcanshop.atlassian.net/browse/YSHOP2-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-608 : COD v2 > Slider - Remove arrows when one image is used 

assets/product.js
=> DARK : fix product price in COD theme V2

assets/product.css, assets/product.js, snippets/product-variants.liquid, styles/product.scss
[YSHOP2-682](https://youcanshop.atlassian.net/browse/YSHOP2-682)
[YSHOP2-682]: https://youcanshop.atlassian.net/browse/YSHOP2-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-682 : COD themes > The price isn't updated when the variants are radio buttons

locales/ar.default.json, locales/en.json, locales/fr.json, snippets/head-config.liquid
[YSHOP2-670](https://youcanshop.atlassian.net/browse/YSHOP2-670)
[YSHOP2-670]: https://youcanshop.atlassian.net/browse/YSHOP2-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-670: Themes > Google Analytics doesn't give the full page url

assets/product.js
=> DARK : COD v2 > fix selected variant on cart drawer

assets/accordion.css, styles/accordion.scss
[YSHOP2-694](https://youcanshop.atlassian.net/browse/YSHOP2-694)
[YSHOP2-694]: https://youcanshop.atlassian.net/browse/YSHOP2-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-694: Accordion text is not updated - Theme 2

assets/subCategory.css, sections/main-collection.liquid, snippets/subCategory.liquid, styles/subCategory.scss
[YSHOP2-702](https://youcanshop.atlassian.net/browse/YSHOP2-702)
[YSHOP2-702]: https://youcanshop.atlassian.net/browse/YSHOP2-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-702: Display the subcategories on the COD themes

assets/product.css, styles/product.scss
[YSHOP2-711](https://youcanshop.atlassian.net/browse/YSHOP2-711)
[YSHOP2-711]: https://youcanshop.atlassian.net/browse/YSHOP2-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-711: Themes Bugs

templates/product.json
[YSHOP2-719](https://youcanshop.atlassian.net/browse/YSHOP2-719)
[YSHOP2-719]: https://youcanshop.atlassian.net/browse/YSHOP2-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-719 : Express checkout stays sticky - theme 2

assets/desktop-slider.css, assets/mobile-slider.css, sections/desktop-slider.liquid, styles/desktop-slider.scss, styles/mobile-slider.scss
[YSHOP2-712](https://youcanshop.atlassian.net/browse/YSHOP2-712)
[YSHOP2-712]: https://youcanshop.atlassian.net/browse/YSHOP2-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-712: Themes - A few settings to add

assets/cart-drawer.js, assets/cart.js, assets/helper.js, assets/main.js, sections/main-navbar.liquid
[YSHOP2-726](https://youcanshop.atlassian.net/browse/YSHOP2-726)
[YSHOP2-726]: https://youcanshop.atlassian.net/browse/YSHOP2-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-726 : themes > prevent opening cart drawer on cart page

templates/index.json
[YSHOP2-730](https://youcanshop.atlassian.net/browse/YSHOP2-730)
[YSHOP2-730]: https://youcanshop.atlassian.net/browse/YSHOP2-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-730: Default theme settings - theme 2

assets/main.css, assets/notice-bar.css, config/settings_data.json, sections/notice-bar.liquid, styles/main.scss, styles/notice-bar.scss
[YSHOP2-826](https://youcanshop.atlassian.net/browse/YSHOP2-826)
[YSHOP2-826]: https://youcanshop.atlassian.net/browse/YSHOP2-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Notice bar

assets/footer.css, config/settings_data.json, sections/main-footer.liquid, styles/footer.scss
[YSHOP2-830](https://youcanshop.atlassian.net/browse/YSHOP2-830)
[YSHOP2-830]: https://youcanshop.atlassian.net/browse/YSHOP2-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-830: Footer

sections/multi-column.liquid
[YSHOP2-831](https://youcanshop.atlassian.net/browse/YSHOP2-831)
[YSHOP2-831]: https://youcanshop.atlassian.net/browse/YSHOP2-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-831: Multi-column

assets/product-column.css, sections/product-column.liquid, snippets/product-home.liquid, styles/product-column.scss, templates/index.json
[YSHOP2-838](https://youcanshop.atlassian.net/browse/YSHOP2-838)
[YSHOP2-838]: https://youcanshop.atlassian.net/browse/YSHOP2-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-838: Product Columns

snippets/reviews.liquid
[YSHOP2-839](https://youcanshop.atlassian.net/browse/YSHOP2-839)
[YSHOP2-839]: https://youcanshop.atlassian.net/browse/YSHOP2-839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-839: Reviews

assets/countdown.css, assets/featured-products.css, sections/featured-product-slider.liquid, snippets/product-preview.liquid, styles/countdown.scss, styles/featured-products.scss
[YSHOP2-832](https://youcanshop.atlassian.net/browse/YSHOP2-832)
Subtask (more like DARK): https://youcanshop.atlassian.net/jira/software/c/projects/YSHOP2/boards/33?modal=detail&selectedIssue=YSHOP2-842
[YSHOP2-832]: https://youcanshop.atlassian.net/browse/YSHOP2-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-832: Update featured products styles

assets/collection-listing.css, assets/main.css, sections/main-list-collections.liquid, snippets/breadcrumbs.liquid, styles/collection-listing.scss, styles/main.scss
[YSHOP2-860](https://youcanshop.atlassian.net/browse/YSHOP2-860)
[YSHOP2-860]: https://youcanshop.atlassian.net/browse/YSHOP2-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-860: Collections Listing

assets/featured-products.css, assets/main.css, sections/feature-products-by-category.liquid, snippets/product-preview.liquid, styles/featured-products.scss, styles/main.scss
[YSHOP2-843](https://youcanshop.atlassian.net/browse/YSHOP2-843)
[YSHOP2-843]: https://youcanshop.atlassian.net/browse/YSHOP2-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-843: Featured products by category

locales/ar.default.json, locales/en.json, locales/fr.json
[YSHOP2-836](https://youcanshop.atlassian.net/browse/YSHOP2-836)
[YSHOP2-836]: https://youcanshop.atlassian.net/browse/YSHOP2-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-836: Update and complete translation files

assets/main.css, assets/product.css, styles/main.scss, styles/product.scss, templates/product.json
[YSHOP2-851](https://youcanshop.atlassian.net/browse/YSHOP2-851)
[YSHOP2-851]: https://youcanshop.atlassian.net/browse/YSHOP2-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-851: Title, Price & Ratings

assets/thankyou.css, sections/thankyou.liquid, styles/thankyou.scss
[YSHOP2-863](https://youcanshop.atlassian.net/browse/YSHOP2-863)
[YSHOP2-863]: https://youcanshop.atlassian.net/browse/YSHOP2-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-863: Upload icon in thank you page - Theme 1 & 2

assets/main.css, snippets/breadcrumbs.liquid, styles/main.scss
[YSHOP2-864](https://youcanshop.atlassian.net/browse/YSHOP2-864)
[YSHOP2-864]: https://youcanshop.atlassian.net/browse/YSHOP2-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-864: Create a reusable breadcrumps partial

assets/featured-collections.css, styles/featured-collections.scss
[YSHOP2-865](https://youcanshop.atlassian.net/browse/YSHOP2-865)
[YSHOP2-865]: https://youcanshop.atlassian.net/browse/YSHOP2-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-865: Featured collections

assets/main.css, assets/product-listing.css, sections/main-collection.liquid, styles/main.scss, styles/product-listing.scss
[YSHOP2-X](https://youcanshop.atlassian.net/browse/YSHOP2-X)
=> Add the category name to the collection template

assets/cart.css, assets/main.css, assets/utils.css, locales/ar.default.json, locales/en.json, locales/fr.json, sections/main-cart.liquid, snippets/breadcrumbs.liquid, snippets/head-config.liquid, styles/cart.scss, styles/main.scss, styles/upsell.scss
[YSHOP2-848](https://youcanshop.atlassian.net/browse/YSHOP2-848)
[YSHOP2-848]: https://youcanshop.atlassian.net/browse/YSHOP2-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-848: Update Cart

locales/ar.default.json, locales/en.json, locales/fr.json, sections/main-cart.liquid, snippets/cart-drawer.liquid
[YSHOP2-867](https://youcanshop.atlassian.net/browse/YSHOP2-867)
[YSHOP2-867]: https://youcanshop.atlassian.net/browse/YSHOP2-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-867: Fix cart drawer english translations

assets/countdown.css, assets/featured-products.css, assets/product.css, sections/product.liquid, snippets/countdown.liquid, styles/countdown.scss, styles/product.scss, templates/product.json
[YSHOP2-852](https://youcanshop.atlassian.net/browse/YSHOP2-852)
[YSHOP2-852]: https://youcanshop.atlassian.net/browse/YSHOP2-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-852: Stock & Countdown timer

assets/footer.css, assets/product-listing.css, sections/featured-products.liquid, sections/main-footer.liquid, styles/footer.scss, styles/product-listing.scss
=> DARK: Fix the responsive on the collection page

assets/product-slider.css, snippets/product-slider.liquid, styles/product-slider.scss
[YSHOP2-833](https://youcanshop.atlassian.net/browse/YSHOP2-833)
This PR addresses this [Issue](https://youcanshop.atlassian.net/browse/YSHOP2-833?focusedCommentId=20229)
-  Visit homepage on a mobile device, or simulate mobile view from theme editor
-  Scroll down to Featured products slider
- For each item. the name, price and compare_at_price (if applicable) should be displayed
[YSHOP2-833]: https://youcanshop.atlassian.net/browse/YSHOP2-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> dark: fix product slider not showing item details

assets/product.css, styles/product.scss
[YSHOP2-870](https://youcanshop.atlassian.net/browse/YSHOP2-870)
[YSHOP2-870]: https://youcanshop.atlassian.net/browse/YSHOP2-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-870: Fix the product Image zoom issue

assets/main.css, assets/product-card.css, assets/product.css, snippets/accordion.liquid, snippets/product-card.liquid, snippets/single-product.liquid, styles/main.scss, styles/product-card.scss, styles/product.scss, templates/product.json
[YSHOP2-853](https://youcanshop.atlassian.net/browse/YSHOP2-853)
[YSHOP2-853]: https://youcanshop.atlassian.net/browse/YSHOP2-853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-853 : theme 2 > Variants, Quantity & Accordion

assets/cart-drawer.css, assets/express-checkout.css, assets/featured-products.css, assets/product-column.css, assets/product-listing.css, assets/product.css, sections/feature-products-by-category.liquid, sections/main-search.liquid, sections/product-column.liquid, sections/product.liquid, sections/thankyou.liquid, snippets/countdown.liquid, snippets/single-product.liquid, styles/cart-drawer.scss, styles/express-checkout.scss, styles/featured-products.scss, styles/product-column.scss, styles/product-listing.scss, styles/product.scss
=> DARK: Theme-2 QA

sections/main-upsell.liquid
[YSHOP2-847](https://youcanshop.atlassian.net/browse/YSHOP2-847?focusedCommentId=20261)
[YSHOP2-847]: https://youcanshop.atlassian.net/browse/YSHOP2-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> dark: change no button color behavior on hover in upsell

assets/main.css, styles/main.scss
[YSHOP2-848](https://youcanshop.atlassian.net/browse/YSHOP2-848)
[YSHOP2-848]: https://youcanshop.atlassian.net/browse/YSHOP2-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> dark: fix input line-height issue on safari

assets/main.css, styles/main.scss
=> YSHOP2-864: Fix breadCrumb LTR direction

assets/cart.css, styles/cart.scss
[YSHOP2-848](https://youcanshop.atlassian.net/browse/YSHOP2-848)
[YSHOP2-848]: https://youcanshop.atlassian.net/browse/YSHOP2-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-848 : Carte page > fix close button direction on LTR

sections/main-collection.liquid, sections/main-upsell.liquid
=> DARK : fix (upsell page, collection page) height when the main body is empty

assets/pages.css, sections/main-page.liquid, snippets/breadcrumbs.liquid, styles/pages.scss
[YSHOP2-871](https://youcanshop.atlassian.net/browse/YSHOP2-871)
[YSHOP2-871]: https://youcanshop.atlassian.net/browse/YSHOP2-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-871: Contact us page

assets/countdown.css, assets/featured-products.css, styles/countdown.scss
[YSHOP2-852](https://youcanshop.atlassian.net/browse/YSHOP2-852)
[YSHOP2-852]: https://youcanshop.atlassian.net/browse/YSHOP2-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DARK: fix the countdown ltr issue

assets/add-to-cart.js, assets/cart-drawer.css, assets/navbar.css, snippets/cart-drawer.liquid, styles/cart-drawer.scss, styles/navbar.scss
[YSHOP2-867](https://youcanshop.atlassian.net/browse/YSHOP2-867?focusedCommentId=20313)
[YSHOP2-867]: https://youcanshop.atlassian.net/browse/YSHOP2-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-867 (Rebase): Update cart drawer styles

assets/add-to-cart.js, assets/cart-drawer.css, assets/reviews.js, sections/product.liquid, snippets/add-to-cart.liquid, snippets/single-product.liquid, styles/cart-drawer.scss, templates/product.json
[YSHOP2-875](https://youcanshop.atlassian.net/browse/YSHOP2-875)
[YSHOP2-875]: https://youcanshop.atlassian.net/browse/YSHOP2-875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-875: theme 2 > Skip Cart

assets/add-to-cart.js, assets/product-slider.css, config/settings_schema.json, locales/ar.default.json, locales/en.json, locales/fr.json, snippets/product-preview.liquid, snippets/product-slider.liquid, styles/product-slider.scss
[YSHOP2-876](https://youcanshop.atlassian.net/browse/YSHOP2-876)
[YSHOP2-876]: https://youcanshop.atlassian.net/browse/YSHOP2-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-876: Direct Add to cart

assets/add-to-cart.js, assets/cart-drawer.css, styles/cart-drawer.scss
=> DARK: Fix the issue when removing in item from the cart

assets/subCategory.css, styles/subCategory.scss
[YSHOP2-984](https://youcanshop.atlassian.net/browse/YSHOP2-984)
[YSHOP2-984]: https://youcanshop.atlassian.net/browse/YSHOP2-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DARK: fix sub categories display

assets/main.css, assets/main.js, layouts/theme.liquid, sections/main-cart.liquid, sections/main-collection.liquid, sections/main-search.liquid, sections/main-upsell.liquid, styles/main.scss
This fix is already made in theme 3, we need to fix the height of the page if there is no content
I also add empty result if their is no items in collection page
=> DARK: theme 2 > fix empty page height

assets/add-to-cart.js
[YSHOP2-987](https://youcanshop.atlassian.net/browse/YSHOP2-987)
[YSHOP2-987]: https://youcanshop.atlassian.net/browse/YSHOP2-987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-987: fix add to cart spinner

assets/cart.css, assets/cart.js, locales/ar.default.json, locales/en.json, locales/fr.json, sections/main-cart.liquid, styles/cart.scss
[YSHOP2-660](https://youcanshop.atlassian.net/browse/YSHOP2-660)
[YSHOP2-660]: https://youcanshop.atlassian.net/browse/YSHOP2-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-660: Can't see the applied coupon on new themes

assets/upsell.css, sections/main-upsell.liquid, styles/upsell.scss
-  [ ] check the upsell page from theme editor
=> DARK : theme 2 > fix upsell page styling

assets/dropdown-menu.js, assets/queries-handler.js, snippets/product-variants.liquid
[YSHOP2-1031](https://youcanshop.atlassian.net/browse/YSHOP2-1031)
[YSHOP2-1031]: https://youcanshop.atlassian.net/browse/YSHOP2-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-1031: COD themes > theme 2 > dropdown menu bugs

assets/express-checkout.js
[Thread link](https://youcan-shop.slack.com/archives/C04CW1478R1/p1700467656598849)
=> DARK: Express checkout display error message

sections/thankyou.liquid
[thread 1](https://youcan-shop.slack.com/archives/C04CW1478R1/p1701420638492819)
=> DARK: Fix thank u page product url link

snippets/cart-drawer.liquid
[Thread link](https://youcan-shop.slack.com/archives/C04BDG9HEB1/p1707468576727519)
=> DARK: Fix the cart drawer issue

assets/express-checkout.css, assets/express-checkout.js, assets/main.css, snippets/express-checkout.liquid, styles/express-checkout.scss, styles/main.scss
[YSHOP2-1372](https://youcanshop.atlassian.net/browse/YSHOP2-1372)
-  go to settings > payment and add a custom field
- try to add different types of fields 
- then verify that the custom fields it's appear on the theme
[YSHOP2-1372]: https://youcanshop.atlassian.net/browse/YSHOP2-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YSHOP2-1372: Add the option to display the states as a drop-down list on the new themes 

sections/featured-products.liquid
https://youcan-shop.slack.com/archives/C04BDG9HEB1/p1711499774678319
-  [ ]  Select featured products section
-  [ ] Try to add more than 25 product block
=> DARK: featured products > add max blocks

assets/main.js, layouts/theme.liquid
[YSHOP2-X](https://youcanshop.atlassian.net/browse/YSHOP2-X)
=> SHOP-1497 : Display error message when total cart amount is greater than max checkout amount
